#! /usr/bin/env python
# Last changed: 2010-05-10 11:42:20 by ralf

import sys, datetime

epoch = datetime.datetime(1970,1,1)

def unts(f):
    while 1:
        line = f.readline()
        if not line:
            return
        try:
            ts, rest = line.split(" ", 1)
            ts = epoch+datetime.timedelta(*divmod(float(ts), 86400))
        except ValueError:
            sys.stdout.write(line)
        else:
            sys.stdout.write("%s %s" % (ts, rest))

    sys.stdout.flush()



def main():
    files = sys.argv[1:]
    if files:
        for x in files:
            unts(open(x, "rb"))
    else:
        unts(sys.stdin)

if __name__=="__main__":
    main()
